<?php

namespace App\Filament\Employee\Resources;

use App\Filament\Employee\Resources\ClientOrderResource\Pages;
use App\Filament\Employee\Resources\ClientOrderResource\RelationManagers;
use App\Models\ClientOrder;
use App\Models\Client;
use App\Models\Service;
use App\Models\Employee;
use Carbon\Carbon;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Filters\Filter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class ClientOrderResource extends Resource
{
    protected static ?string $model = ClientOrder::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('client_id')
                    ->label('Клиент')
                    ->options(Client::all()->pluck('name', 'id'))
                    ->disabled(),
                Forms\Components\Select::make('employee_id')
                    ->label('Звукорежиссёр')
                    ->options(Employee::where('is_working', true)->pluck('name', 'id'))
                    ->required()
                    ->reactive()
                    ->afterStateUpdated(fn ($state, callable $set) => $set('disabled_dates', self::getDisabledDates($state))),
                Forms\Components\Select::make('service_id')
                    ->label('Услуга')
                    ->options(Service::where('is_active', true)->pluck('name', 'id'))
                    ->required()
                    ->reactive()
                    ->afterStateUpdated(function ($state, callable $set) {
                        $service = Service::find($state);
                        $set('price', $service ? $service->price : null);
                    }),
                Forms\Components\TextInput::make('price')
                    ->label('Цена')
                    ->disabled(),
                Forms\Components\DatePicker::make('date_of_order')
                    ->label('Дата')
                    ->required()
                    ->reactive()
                    ->minDate(Carbon::now()) // Отключение прошлых дат
                    ->disabledDates(fn ($get) => $get('disabled_dates') ?? [])
                    ->native(false) // Отключение нативного выбора даты
                    ->format('Y-m-d'), // Убедитесь, что дата сохраняется в правильном формате
                Forms\Components\FileUpload::make('audio_file')
                    ->label('Аудиофайл')
                    ->disabled()
                    ->disk('public')
                    ->directory('audio_files')
                    ->acceptedFileTypes(['audio/*'])
                    ->maxSize(10240) // 10 MB
                    ->preserveFilenames()
                    ->storeFileNamesIn('original_name')
                    ->visibility('public')
                    ->getUploadedFileNameForStorageUsing(function ($file): string {
                        $fileName = $file->getClientOriginalName();
                        $extension = pathinfo($fileName, PATHINFO_EXTENSION);
                        $name = pathinfo($fileName, PATHINFO_FILENAME);
                        $slug = Str::slug($name, '-');

                        $timestamp = now()->timestamp;
                        $storedFileName = "{$timestamp}-{$slug}.{$extension}";
                        Log::info('Stored file name: ' . $storedFileName);
                        return $storedFileName;
                    })
                    ->openable()
                    ->downloadable(),
                Forms\Components\Textarea::make('description')
                    ->label('Описание'),
                Forms\Components\Select::make('status')
                    ->label('Статус заказа')
                    ->options([
                        'Не обработан' => 'Не обработан',
                        'Выполнен' => 'Выполнен',
                        'Подтверждён' => 'Подтверждён',
                    ])
                    ->required()
                    ->default('Ожидает обработки')
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('employee_id',auth()->id());
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('clients.name')->label('Клиент')->searchable(),
                Tables\Columns\TextColumn::make('employees.name')->label('Звукорежиссёр')->searchable(),
                Tables\Columns\TextColumn::make('services.name')->label('Услуга')->searchable(),
                Tables\Columns\TextColumn::make('services.price')->label('Цена')->searchable(),
                Tables\Columns\TextColumn::make('date_of_order')->label('Дата'),
                Tables\Columns\TextColumn::make('status')->label('Статус')->searchable(),
                Tables\Columns\TextColumn::make('description')->label('Описание')->searchable(),
                Tables\Columns\ViewColumn::make('audio_file')->label('Аудиофайл')
                    ->view('vendor.filament-panels.components.audio-player')
                    ->url(fn($record) => (string) $record->audio_file_url ?? ''),
            ])
            ->filters([
                SelectFilter::make('employee_id')
                    ->label('Звукорежиссёр')
                    ->options(Employee::all()->pluck('name', 'id')),
                SelectFilter::make('service_id')
                    ->label('Услуга')
                    ->options(Service::all()->pluck('name', 'id')),
                SelectFilter::make('status')
                    ->label('Статус заказа')
                    ->options([
                        'Не обработан' => 'Не обработан',
                        'Выполнен' => 'Выполнен',
                        'Подтверждён' => 'Подтверждён',
                    ]),
                Filter::make('date_of_order')
                    ->label('Дата заказа')
                    ->form([
                        Forms\Components\DatePicker::make('date_from')
                            ->label('С даты'),
                        Forms\Components\DatePicker::make('date_to')
                            ->label('По дату'),
                    ])
                    ->query(function (Builder $query, array $data) {
                        return $query
                            ->when($data['date_from'], fn ($query, $date) => $query->whereDate('date_of_order', '>=', $date))
                            ->when($data['date_to'], fn ($query, $date) => $query->whereDate('date_of_order', '<=', $date));
                    }),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getDisabledDates($employeeId)
    {
        if (!$employeeId) {
            return [];
        }

        $dates = ClientOrder::where('employee_id', $employeeId)->pluck('date_of_order')->toArray();
        $pastDates = self::getPastDates();

        return array_merge($dates, $pastDates);
    }

    public static function getPastDates()
    {
        $today = Carbon::today();
        $dates = [];

        for ($date = Carbon::now()->subYear(); $date->lte($today); $date->addDay()) {
            if ($date->lt($today)) {
                $dates[] = $date->format('Y-m-d');
            }
        }

        return $dates;
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListClientOrders::route('/'),
            'create' => Pages\CreateClientOrder::route('/create'),
            'edit' => Pages\EditClientOrder::route('/{record}/edit'),
        ];
    }

    public static function getNavigationLabel(): string
    {
        return 'Заказы клиентов';
    }

    public static function getLabel(): string
    {
        return 'Заказ клиента';
    }

    public static function getPluralLabel(): string
    {
        return 'Заказы клиентов';
    }
}
